name: "Image Resizer RS"
description: "Resize all images from the source directory that do not exist in the target directory to the specified widths—skipping already processed files and preserving the aspect ratio."
author: "Elar Saks"

branding:
  icon: "image"
  color: "blue"

inputs:
  source-dir:
    description: "Directory containing original images"
    required: true
  sizes:
    description: "Comma-separated list of widths to generate (e.g. 64,128,256)"
    required: true
  output-dir:
    description: "Directory where resized images will be written"
    required: true

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --source-dir=${{ inputs.source-dir }}
    - --sizes=${{ inputs.sizes }}
    - --output-dir=${{ inputs.output-dir }}
