[package]
name = "image-resizer"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1"
clap = { version = "4", features = ["derive", "env"] }
image = { version = "0.24", features = ["png", "jpeg", "gif", "bmp"] }
log = "0.4"
env_logger = "0.10"

[dev-dependencies]
tempfile = "3"
